# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import db_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='db_shop.proto',
  package='',
  serialized_pb='\n\rdb_shop.proto\x1a\rdb_base.proto\"/\n\tPBDBGoods\x12\x10\n\x08goods_id\x18\x01 \x01(\r\x12\x10\n\x08sold_out\x18\x02 \x01(\r\"I\n\x0ePBDBLimitGoods\x12\x10\n\x08goods_id\x18\x01 \x01(\r\x12\x13\n\x0bsold_nubmer\x18\x02 \x01(\r\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\r\"z\n\x08PBDBShop\x12\x0f\n\x07shop_id\x18\x01 \x01(\r\x12\x19\n\x05goods\x18\x02 \x03(\x0b\x32\n.PBDBGoods\x12\x12\n\nflush_time\x18\x03 \x01(\r\x12\x13\n\x0b\x66lush_count\x18\x04 \x01(\r\x12\x19\n\x11money_flush_count\x18\x05 \x01(\r\"M\n\x0cPBDBShopInfo\x12\x17\n\x04shop\x18\x01 \x03(\x0b\x32\t.PBDBShop\x12$\n\x0blimit_goods\x18\x02 \x03(\x0b\x32\x0f.PBDBLimitGoods\">\n\x14PBDBExchangeShopData\x12&\n\ngoods_list\x18\x01 \x03(\x0b\x32\x12.PBDBExchangeGoods\"O\n\x11PBDBExchangeGoods\x12\x13\n\x0b\x65x_goods_id\x18\x01 \x01(\x11\x12\x10\n\x08\x65x_count\x18\x02 \x01(\x11\x12\x13\n\x0b\x65x_end_time\x18\x03 \x01(\rB\x02H\x01')




_PBDBGOODS = descriptor.Descriptor(
  name='PBDBGoods',
  full_name='PBDBGoods',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='goods_id', full_name='PBDBGoods.goods_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sold_out', full_name='PBDBGoods.sold_out', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=79,
)


_PBDBLIMITGOODS = descriptor.Descriptor(
  name='PBDBLimitGoods',
  full_name='PBDBLimitGoods',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='goods_id', full_name='PBDBLimitGoods.goods_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sold_nubmer', full_name='PBDBLimitGoods.sold_nubmer', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_time', full_name='PBDBLimitGoods.end_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=81,
  serialized_end=154,
)


_PBDBSHOP = descriptor.Descriptor(
  name='PBDBShop',
  full_name='PBDBShop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='shop_id', full_name='PBDBShop.shop_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='goods', full_name='PBDBShop.goods', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flush_time', full_name='PBDBShop.flush_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flush_count', full_name='PBDBShop.flush_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='money_flush_count', full_name='PBDBShop.money_flush_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=156,
  serialized_end=278,
)


_PBDBSHOPINFO = descriptor.Descriptor(
  name='PBDBShopInfo',
  full_name='PBDBShopInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='shop', full_name='PBDBShopInfo.shop', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='limit_goods', full_name='PBDBShopInfo.limit_goods', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=280,
  serialized_end=357,
)


_PBDBEXCHANGESHOPDATA = descriptor.Descriptor(
  name='PBDBExchangeShopData',
  full_name='PBDBExchangeShopData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='goods_list', full_name='PBDBExchangeShopData.goods_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=359,
  serialized_end=421,
)


_PBDBEXCHANGEGOODS = descriptor.Descriptor(
  name='PBDBExchangeGoods',
  full_name='PBDBExchangeGoods',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ex_goods_id', full_name='PBDBExchangeGoods.ex_goods_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ex_count', full_name='PBDBExchangeGoods.ex_count', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ex_end_time', full_name='PBDBExchangeGoods.ex_end_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=423,
  serialized_end=502,
)

_PBDBSHOP.fields_by_name['goods'].message_type = _PBDBGOODS
_PBDBSHOPINFO.fields_by_name['shop'].message_type = _PBDBSHOP
_PBDBSHOPINFO.fields_by_name['limit_goods'].message_type = _PBDBLIMITGOODS
_PBDBEXCHANGESHOPDATA.fields_by_name['goods_list'].message_type = _PBDBEXCHANGEGOODS
DESCRIPTOR.message_types_by_name['PBDBGoods'] = _PBDBGOODS
DESCRIPTOR.message_types_by_name['PBDBLimitGoods'] = _PBDBLIMITGOODS
DESCRIPTOR.message_types_by_name['PBDBShop'] = _PBDBSHOP
DESCRIPTOR.message_types_by_name['PBDBShopInfo'] = _PBDBSHOPINFO
DESCRIPTOR.message_types_by_name['PBDBExchangeShopData'] = _PBDBEXCHANGESHOPDATA
DESCRIPTOR.message_types_by_name['PBDBExchangeGoods'] = _PBDBEXCHANGEGOODS

class PBDBGoods(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDBGOODS
  
  # @@protoc_insertion_point(class_scope:PBDBGoods)

class PBDBLimitGoods(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDBLIMITGOODS
  
  # @@protoc_insertion_point(class_scope:PBDBLimitGoods)

class PBDBShop(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDBSHOP
  
  # @@protoc_insertion_point(class_scope:PBDBShop)

class PBDBShopInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDBSHOPINFO
  
  # @@protoc_insertion_point(class_scope:PBDBShopInfo)

class PBDBExchangeShopData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDBEXCHANGESHOPDATA
  
  # @@protoc_insertion_point(class_scope:PBDBExchangeShopData)

class PBDBExchangeGoods(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDBEXCHANGEGOODS
  
  # @@protoc_insertion_point(class_scope:PBDBExchangeGoods)

# @@protoc_insertion_point(module_scope)
