# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import msg_base_pb2
import msg_common_pb2
import tmpl_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_change_camp.proto',
  package='',
  serialized_pb='\n\x15msg_change_camp.proto\x1a\x0emsg_base.proto\x1a\x10msg_common.proto\x1a\x0ftmpl_base.proto\"\x1c\n\x1aPBMsgCheckTransCampRequest\"W\n\x1bPBMsgCheckTransCampResponse\x12\x10\n\x08ret_code\x18\x01 \x01(\x11\x12&\n\tcamp_list\x18\x02 \x03(\x0b\x32\x13.PBMsgTransCampInfo\"\xac\x01\n\x12PBMsgTransCampInfo\x12\x0f\n\x07\x63\x61mp_id\x18\x01 \x01(\x11\x12\x12\n\ncamp_score\x18\x02 \x01(\x11\x12.\n\tcamp_cost\x18\x03 \x01(\x0b\x32\x1b.PBTemplateItemQuantityList\x12.\n\tcamp_gain\x18\x04 \x01(\x0b\x32\x1b.PBTemplateItemQuantityList\x12\x11\n\tcamp_rank\x18\x05 \x01(\x11\"2\n\x1aPBMsgReadyTransCampRequest\x12\x14\n\x0c\x64\x65st_camp_id\x18\x01 \x01(\x11\"E\n\x1bPBMsgReadyTransCampResponse\x12\x10\n\x08ret_code\x18\x01 \x01(\x11\x12\x14\n\x0c\x64\x65st_camp_id\x18\x02 \x01(\x11\"3\n\x1bPBMsgTransCampSingleRequest\x12\x14\n\x0c\x64\x65st_camp_id\x18\x01 \x01(\x11\"0\n\x1cPBMsgTransCampSingleResponse\x12\x10\n\x08ret_code\x18\x01 \x01(\x11\"3\n\x1bPBMsgTransCampLeaderRequest\x12\x14\n\x0c\x64\x65st_camp_id\x18\x01 \x01(\x11\"0\n\x1cPBMsgTransCampLeaderResponse\x12\x10\n\x08ret_code\x18\x01 \x01(\x11\"k\n\x1aPBMsgTransCampMemberNotice\x12\x10\n\x08ret_code\x18\x01 \x01(\x11\x12\x13\n\x0bparter_name\x18\x02 \x01(\t\x12\x11\n\tdest_camp\x18\x03 \x01(\x11\x12\x13\n\x0bwait_second\x18\x04 \x01(\x11\"/\n\x18PBMsgTransCampWaitNotice\x12\x13\n\x0bwait_second\x18\x01 \x01(\x11\"\x1b\n\x19PBMsgTransMemberOkRequest\".\n\x1aPBMsgTransMemberOkResponse\x12\x10\n\x08ret_code\x18\x01 \x01(\x11\"\x1f\n\x1dPBMsgTransMemberCancelRequest\"2\n\x1ePBMsgTransMemberCancelResponse\x12\x10\n\x08ret_code\x18\x01 \x01(\x11\"2\n\x1bPBMsgTransCampSuccessNotice\x12\x13\n\x0bnew_camp_id\x18\x01 \x01(\x11')




_PBMSGCHECKTRANSCAMPREQUEST = descriptor.Descriptor(
  name='PBMsgCheckTransCampRequest',
  full_name='PBMsgCheckTransCampRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=104,
)


_PBMSGCHECKTRANSCAMPRESPONSE = descriptor.Descriptor(
  name='PBMsgCheckTransCampResponse',
  full_name='PBMsgCheckTransCampResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgCheckTransCampResponse.ret_code', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='camp_list', full_name='PBMsgCheckTransCampResponse.camp_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=106,
  serialized_end=193,
)


_PBMSGTRANSCAMPINFO = descriptor.Descriptor(
  name='PBMsgTransCampInfo',
  full_name='PBMsgTransCampInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='camp_id', full_name='PBMsgTransCampInfo.camp_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='camp_score', full_name='PBMsgTransCampInfo.camp_score', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='camp_cost', full_name='PBMsgTransCampInfo.camp_cost', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='camp_gain', full_name='PBMsgTransCampInfo.camp_gain', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='camp_rank', full_name='PBMsgTransCampInfo.camp_rank', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=196,
  serialized_end=368,
)


_PBMSGREADYTRANSCAMPREQUEST = descriptor.Descriptor(
  name='PBMsgReadyTransCampRequest',
  full_name='PBMsgReadyTransCampRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dest_camp_id', full_name='PBMsgReadyTransCampRequest.dest_camp_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=370,
  serialized_end=420,
)


_PBMSGREADYTRANSCAMPRESPONSE = descriptor.Descriptor(
  name='PBMsgReadyTransCampResponse',
  full_name='PBMsgReadyTransCampResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgReadyTransCampResponse.ret_code', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dest_camp_id', full_name='PBMsgReadyTransCampResponse.dest_camp_id', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=422,
  serialized_end=491,
)


_PBMSGTRANSCAMPSINGLEREQUEST = descriptor.Descriptor(
  name='PBMsgTransCampSingleRequest',
  full_name='PBMsgTransCampSingleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dest_camp_id', full_name='PBMsgTransCampSingleRequest.dest_camp_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=493,
  serialized_end=544,
)


_PBMSGTRANSCAMPSINGLERESPONSE = descriptor.Descriptor(
  name='PBMsgTransCampSingleResponse',
  full_name='PBMsgTransCampSingleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgTransCampSingleResponse.ret_code', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=546,
  serialized_end=594,
)


_PBMSGTRANSCAMPLEADERREQUEST = descriptor.Descriptor(
  name='PBMsgTransCampLeaderRequest',
  full_name='PBMsgTransCampLeaderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dest_camp_id', full_name='PBMsgTransCampLeaderRequest.dest_camp_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=596,
  serialized_end=647,
)


_PBMSGTRANSCAMPLEADERRESPONSE = descriptor.Descriptor(
  name='PBMsgTransCampLeaderResponse',
  full_name='PBMsgTransCampLeaderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgTransCampLeaderResponse.ret_code', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=649,
  serialized_end=697,
)


_PBMSGTRANSCAMPMEMBERNOTICE = descriptor.Descriptor(
  name='PBMsgTransCampMemberNotice',
  full_name='PBMsgTransCampMemberNotice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgTransCampMemberNotice.ret_code', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parter_name', full_name='PBMsgTransCampMemberNotice.parter_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dest_camp', full_name='PBMsgTransCampMemberNotice.dest_camp', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wait_second', full_name='PBMsgTransCampMemberNotice.wait_second', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=699,
  serialized_end=806,
)


_PBMSGTRANSCAMPWAITNOTICE = descriptor.Descriptor(
  name='PBMsgTransCampWaitNotice',
  full_name='PBMsgTransCampWaitNotice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='wait_second', full_name='PBMsgTransCampWaitNotice.wait_second', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=808,
  serialized_end=855,
)


_PBMSGTRANSMEMBEROKREQUEST = descriptor.Descriptor(
  name='PBMsgTransMemberOkRequest',
  full_name='PBMsgTransMemberOkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=857,
  serialized_end=884,
)


_PBMSGTRANSMEMBEROKRESPONSE = descriptor.Descriptor(
  name='PBMsgTransMemberOkResponse',
  full_name='PBMsgTransMemberOkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgTransMemberOkResponse.ret_code', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=886,
  serialized_end=932,
)


_PBMSGTRANSMEMBERCANCELREQUEST = descriptor.Descriptor(
  name='PBMsgTransMemberCancelRequest',
  full_name='PBMsgTransMemberCancelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=934,
  serialized_end=965,
)


_PBMSGTRANSMEMBERCANCELRESPONSE = descriptor.Descriptor(
  name='PBMsgTransMemberCancelResponse',
  full_name='PBMsgTransMemberCancelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgTransMemberCancelResponse.ret_code', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=967,
  serialized_end=1017,
)


_PBMSGTRANSCAMPSUCCESSNOTICE = descriptor.Descriptor(
  name='PBMsgTransCampSuccessNotice',
  full_name='PBMsgTransCampSuccessNotice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='new_camp_id', full_name='PBMsgTransCampSuccessNotice.new_camp_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=1019,
  serialized_end=1069,
)

_PBMSGCHECKTRANSCAMPRESPONSE.fields_by_name['camp_list'].message_type = _PBMSGTRANSCAMPINFO
_PBMSGTRANSCAMPINFO.fields_by_name['camp_cost'].message_type = tmpl_base_pb2._PBTEMPLATEITEMQUANTITYLIST
_PBMSGTRANSCAMPINFO.fields_by_name['camp_gain'].message_type = tmpl_base_pb2._PBTEMPLATEITEMQUANTITYLIST
DESCRIPTOR.message_types_by_name['PBMsgCheckTransCampRequest'] = _PBMSGCHECKTRANSCAMPREQUEST
DESCRIPTOR.message_types_by_name['PBMsgCheckTransCampResponse'] = _PBMSGCHECKTRANSCAMPRESPONSE
DESCRIPTOR.message_types_by_name['PBMsgTransCampInfo'] = _PBMSGTRANSCAMPINFO
DESCRIPTOR.message_types_by_name['PBMsgReadyTransCampRequest'] = _PBMSGREADYTRANSCAMPREQUEST
DESCRIPTOR.message_types_by_name['PBMsgReadyTransCampResponse'] = _PBMSGREADYTRANSCAMPRESPONSE
DESCRIPTOR.message_types_by_name['PBMsgTransCampSingleRequest'] = _PBMSGTRANSCAMPSINGLEREQUEST
DESCRIPTOR.message_types_by_name['PBMsgTransCampSingleResponse'] = _PBMSGTRANSCAMPSINGLERESPONSE
DESCRIPTOR.message_types_by_name['PBMsgTransCampLeaderRequest'] = _PBMSGTRANSCAMPLEADERREQUEST
DESCRIPTOR.message_types_by_name['PBMsgTransCampLeaderResponse'] = _PBMSGTRANSCAMPLEADERRESPONSE
DESCRIPTOR.message_types_by_name['PBMsgTransCampMemberNotice'] = _PBMSGTRANSCAMPMEMBERNOTICE
DESCRIPTOR.message_types_by_name['PBMsgTransCampWaitNotice'] = _PBMSGTRANSCAMPWAITNOTICE
DESCRIPTOR.message_types_by_name['PBMsgTransMemberOkRequest'] = _PBMSGTRANSMEMBEROKREQUEST
DESCRIPTOR.message_types_by_name['PBMsgTransMemberOkResponse'] = _PBMSGTRANSMEMBEROKRESPONSE
DESCRIPTOR.message_types_by_name['PBMsgTransMemberCancelRequest'] = _PBMSGTRANSMEMBERCANCELREQUEST
DESCRIPTOR.message_types_by_name['PBMsgTransMemberCancelResponse'] = _PBMSGTRANSMEMBERCANCELRESPONSE
DESCRIPTOR.message_types_by_name['PBMsgTransCampSuccessNotice'] = _PBMSGTRANSCAMPSUCCESSNOTICE

class PBMsgCheckTransCampRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGCHECKTRANSCAMPREQUEST
  
  # @@protoc_insertion_point(class_scope:PBMsgCheckTransCampRequest)

class PBMsgCheckTransCampResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGCHECKTRANSCAMPRESPONSE
  
  # @@protoc_insertion_point(class_scope:PBMsgCheckTransCampResponse)

class PBMsgTransCampInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSCAMPINFO
  
  # @@protoc_insertion_point(class_scope:PBMsgTransCampInfo)

class PBMsgReadyTransCampRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREADYTRANSCAMPREQUEST
  
  # @@protoc_insertion_point(class_scope:PBMsgReadyTransCampRequest)

class PBMsgReadyTransCampResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGREADYTRANSCAMPRESPONSE
  
  # @@protoc_insertion_point(class_scope:PBMsgReadyTransCampResponse)

class PBMsgTransCampSingleRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSCAMPSINGLEREQUEST
  
  # @@protoc_insertion_point(class_scope:PBMsgTransCampSingleRequest)

class PBMsgTransCampSingleResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSCAMPSINGLERESPONSE
  
  # @@protoc_insertion_point(class_scope:PBMsgTransCampSingleResponse)

class PBMsgTransCampLeaderRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSCAMPLEADERREQUEST
  
  # @@protoc_insertion_point(class_scope:PBMsgTransCampLeaderRequest)

class PBMsgTransCampLeaderResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSCAMPLEADERRESPONSE
  
  # @@protoc_insertion_point(class_scope:PBMsgTransCampLeaderResponse)

class PBMsgTransCampMemberNotice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSCAMPMEMBERNOTICE
  
  # @@protoc_insertion_point(class_scope:PBMsgTransCampMemberNotice)

class PBMsgTransCampWaitNotice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSCAMPWAITNOTICE
  
  # @@protoc_insertion_point(class_scope:PBMsgTransCampWaitNotice)

class PBMsgTransMemberOkRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSMEMBEROKREQUEST
  
  # @@protoc_insertion_point(class_scope:PBMsgTransMemberOkRequest)

class PBMsgTransMemberOkResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSMEMBEROKRESPONSE
  
  # @@protoc_insertion_point(class_scope:PBMsgTransMemberOkResponse)

class PBMsgTransMemberCancelRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSMEMBERCANCELREQUEST
  
  # @@protoc_insertion_point(class_scope:PBMsgTransMemberCancelRequest)

class PBMsgTransMemberCancelResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSMEMBERCANCELRESPONSE
  
  # @@protoc_insertion_point(class_scope:PBMsgTransMemberCancelResponse)

class PBMsgTransCampSuccessNotice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTRANSCAMPSUCCESSNOTICE
  
  # @@protoc_insertion_point(class_scope:PBMsgTransCampSuccessNotice)

# @@protoc_insertion_point(module_scope)
