# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import msg_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_character_title.proto',
  package='',
  serialized_pb='\n\x19msg_character_title.proto\x1a\x0emsg_base.proto\"L\n\x17PBMsgChangeTitleRequest\x12\x13\n\x0btitle_sheet\x18\x01 \x01(\r\x12\x1c\n\x04type\x18\x02 \x01(\x0e\x32\x0e.EUseTitleType\",\n\x18PBMsgChangeTitleResponse\x12\x10\n\x08ret_code\x18\x01 \x01(\x11\"\x9e\x01\n\x14PBCharacterTitleInfo\x12\x13\n\x0btitle_sheet\x18\x01 \x01(\r\x12\x11\n\tis_active\x18\x02 \x01(\x08\x12\x18\n\x10is_use_apperance\x18\x03 \x01(\x08\x12\x13\n\x0bis_use_buff\x18\x04 \x01(\x08\x12\x16\n\x0eremaining_time\x18\x05 \x01(\r\x12\x17\n\x0fis_first_active\x18\x06 \x01(\x08\";\n\x14PBMsgTitleInfoNotice\x12#\n\x04info\x18\x01 \x03(\x0b\x32\x15.PBCharacterTitleInfo*i\n\rEUseTitleType\x12\x16\n\x12\x45UseType_Apperance\x10\x01\x12\x11\n\rEUseType_Buff\x10\x02\x12\x18\n\x14\x45UnuseType_Apperance\x10\x03\x12\x13\n\x0f\x45UnuseType_Buff\x10\x04')

_EUSETITLETYPE = descriptor.EnumDescriptor(
  name='EUseTitleType',
  full_name='EUseTitleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='EUseType_Apperance', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EUseType_Buff', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EUnuseType_Apperance', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EUnuseType_Buff', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=391,
  serialized_end=496,
)


EUseType_Apperance = 1
EUseType_Buff = 2
EUnuseType_Apperance = 3
EUnuseType_Buff = 4



_PBMSGCHANGETITLEREQUEST = descriptor.Descriptor(
  name='PBMsgChangeTitleRequest',
  full_name='PBMsgChangeTitleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='title_sheet', full_name='PBMsgChangeTitleRequest.title_sheet', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='PBMsgChangeTitleRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=121,
)


_PBMSGCHANGETITLERESPONSE = descriptor.Descriptor(
  name='PBMsgChangeTitleResponse',
  full_name='PBMsgChangeTitleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgChangeTitleResponse.ret_code', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=123,
  serialized_end=167,
)


_PBCHARACTERTITLEINFO = descriptor.Descriptor(
  name='PBCharacterTitleInfo',
  full_name='PBCharacterTitleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='title_sheet', full_name='PBCharacterTitleInfo.title_sheet', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_active', full_name='PBCharacterTitleInfo.is_active', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_use_apperance', full_name='PBCharacterTitleInfo.is_use_apperance', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_use_buff', full_name='PBCharacterTitleInfo.is_use_buff', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='remaining_time', full_name='PBCharacterTitleInfo.remaining_time', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_first_active', full_name='PBCharacterTitleInfo.is_first_active', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=170,
  serialized_end=328,
)


_PBMSGTITLEINFONOTICE = descriptor.Descriptor(
  name='PBMsgTitleInfoNotice',
  full_name='PBMsgTitleInfoNotice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='info', full_name='PBMsgTitleInfoNotice.info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=330,
  serialized_end=389,
)

_PBMSGCHANGETITLEREQUEST.fields_by_name['type'].enum_type = _EUSETITLETYPE
_PBMSGTITLEINFONOTICE.fields_by_name['info'].message_type = _PBCHARACTERTITLEINFO
DESCRIPTOR.message_types_by_name['PBMsgChangeTitleRequest'] = _PBMSGCHANGETITLEREQUEST
DESCRIPTOR.message_types_by_name['PBMsgChangeTitleResponse'] = _PBMSGCHANGETITLERESPONSE
DESCRIPTOR.message_types_by_name['PBCharacterTitleInfo'] = _PBCHARACTERTITLEINFO
DESCRIPTOR.message_types_by_name['PBMsgTitleInfoNotice'] = _PBMSGTITLEINFONOTICE

class PBMsgChangeTitleRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGCHANGETITLEREQUEST
  
  # @@protoc_insertion_point(class_scope:PBMsgChangeTitleRequest)

class PBMsgChangeTitleResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGCHANGETITLERESPONSE
  
  # @@protoc_insertion_point(class_scope:PBMsgChangeTitleResponse)

class PBCharacterTitleInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCHARACTERTITLEINFO
  
  # @@protoc_insertion_point(class_scope:PBCharacterTitleInfo)

class PBMsgTitleInfoNotice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMSGTITLEINFONOTICE
  
  # @@protoc_insertion_point(class_scope:PBMsgTitleInfoNotice)

# @@protoc_insertion_point(module_scope)
