# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import msg_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_dimension.proto',
  package='',
  serialized_pb='\n\x13msg_dimension.proto\x1a\x0emsg_base.proto\"!\n\x10PBDimensionHello\x12\r\n\x05hello\x18\x01 \x01(\t\"4\n\x0fPBDimensionChar\x12\x0f\n\x07role_id\x18\x01 \x01(\x04\x12\x10\n\x08shard_id\x18\x02 \x01(\r')




_PBDIMENSIONHELLO = descriptor.Descriptor(
  name='PBDimensionHello',
  full_name='PBDimensionHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hello', full_name='PBDimensionHello.hello', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=72,
)


_PBDIMENSIONCHAR = descriptor.Descriptor(
  name='PBDimensionChar',
  full_name='PBDimensionChar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='role_id', full_name='PBDimensionChar.role_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shard_id', full_name='PBDimensionChar.shard_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['PBDimensionHello'] = _PBDIMENSIONHELLO
DESCRIPTOR.message_types_by_name['PBDimensionChar'] = _PBDIMENSIONCHAR

class PBDimensionHello(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDIMENSIONHELLO
  
  # @@protoc_insertion_point(class_scope:PBDimensionHello)

class PBDimensionChar(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDIMENSIONCHAR
  
  # @@protoc_insertion_point(class_scope:PBDimensionChar)

# @@protoc_insertion_point(module_scope)
