# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tmpl_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_change_job.proto',
  package='',
  serialized_pb='\n\x15tmpl_change_job.proto\x1a\x0ftmpl_base.proto\"\xa4\x02\n\x0ePBChangeJobCfg\x12\x15\n\rrequire_level\x18\x01 \x01(\x11\x12\x1c\n\x14money_remission_rate\x18\x02 \x01(\x11\x12\x1d\n\x15zhenqi_remission_rate\x18\x03 \x01(\x11\x12#\n\tcost_list\x18\x04 \x03(\x0b\x32\x10.PBChangeJobCost\x12(\n\tbook_list\x18\x05 \x03(\x0b\x32\x15.PBRoleJuejiSKillBook\x12\r\n\x05times\x18\x06 \x01(\x11\x12.\n\x0fmoney_item_list\x18\x07 \x03(\x0b\x32\x15.PBChangeJobMoneyItem\x12\x30\n\x10zhenqi_item_list\x18\x08 \x03(\x0b\x32\x16.PBChangeJobZhenQiItem\"5\n\x0fPBChangeJobCost\x12\x10\n\x08sheet_id\x18\x01 \x01(\t\x12\x10\n\x08\x63ost_num\x18\x02 \x01(\x11\"D\n\x14PBRoleJuejiSKillBook\x12\x0c\n\x04role\x18\x01 \x01(\x11\x12\x1e\n\x04\x62ook\x18\x02 \x03(\x0b\x32\x10.PBSkillBookList\"6\n\x0fPBSkillBookList\x12\x0f\n\x07\x62ook_lv\x18\x01 \x01(\x11\x12\x12\n\nbook_sheet\x18\x02 \x01(\t\"@\n\x14PBChangeJobMoneyItem\x12\x16\n\x0e\x65xchange_vaule\x18\x01 \x01(\x11\x12\x10\n\x08sheet_id\x18\x02 \x01(\t\"A\n\x15PBChangeJobZhenQiItem\x12\x16\n\x0e\x65xchange_vaule\x18\x01 \x01(\x11\x12\x10\n\x08sheet_id\x18\x02 \x01(\t')




_PBCHANGEJOBCFG = descriptor.Descriptor(
  name='PBChangeJobCfg',
  full_name='PBChangeJobCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='require_level', full_name='PBChangeJobCfg.require_level', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='money_remission_rate', full_name='PBChangeJobCfg.money_remission_rate', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='zhenqi_remission_rate', full_name='PBChangeJobCfg.zhenqi_remission_rate', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cost_list', full_name='PBChangeJobCfg.cost_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='book_list', full_name='PBChangeJobCfg.book_list', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='times', full_name='PBChangeJobCfg.times', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='money_item_list', full_name='PBChangeJobCfg.money_item_list', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='zhenqi_item_list', full_name='PBChangeJobCfg.zhenqi_item_list', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=335,
)


_PBCHANGEJOBCOST = descriptor.Descriptor(
  name='PBChangeJobCost',
  full_name='PBChangeJobCost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sheet_id', full_name='PBChangeJobCost.sheet_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cost_num', full_name='PBChangeJobCost.cost_num', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=337,
  serialized_end=390,
)


_PBROLEJUEJISKILLBOOK = descriptor.Descriptor(
  name='PBRoleJuejiSKillBook',
  full_name='PBRoleJuejiSKillBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='role', full_name='PBRoleJuejiSKillBook.role', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='book', full_name='PBRoleJuejiSKillBook.book', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=392,
  serialized_end=460,
)


_PBSKILLBOOKLIST = descriptor.Descriptor(
  name='PBSkillBookList',
  full_name='PBSkillBookList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='book_lv', full_name='PBSkillBookList.book_lv', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='book_sheet', full_name='PBSkillBookList.book_sheet', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=462,
  serialized_end=516,
)


_PBCHANGEJOBMONEYITEM = descriptor.Descriptor(
  name='PBChangeJobMoneyItem',
  full_name='PBChangeJobMoneyItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='exchange_vaule', full_name='PBChangeJobMoneyItem.exchange_vaule', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sheet_id', full_name='PBChangeJobMoneyItem.sheet_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=518,
  serialized_end=582,
)


_PBCHANGEJOBZHENQIITEM = descriptor.Descriptor(
  name='PBChangeJobZhenQiItem',
  full_name='PBChangeJobZhenQiItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='exchange_vaule', full_name='PBChangeJobZhenQiItem.exchange_vaule', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sheet_id', full_name='PBChangeJobZhenQiItem.sheet_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=584,
  serialized_end=649,
)

_PBCHANGEJOBCFG.fields_by_name['cost_list'].message_type = _PBCHANGEJOBCOST
_PBCHANGEJOBCFG.fields_by_name['book_list'].message_type = _PBROLEJUEJISKILLBOOK
_PBCHANGEJOBCFG.fields_by_name['money_item_list'].message_type = _PBCHANGEJOBMONEYITEM
_PBCHANGEJOBCFG.fields_by_name['zhenqi_item_list'].message_type = _PBCHANGEJOBZHENQIITEM
_PBROLEJUEJISKILLBOOK.fields_by_name['book'].message_type = _PBSKILLBOOKLIST
DESCRIPTOR.message_types_by_name['PBChangeJobCfg'] = _PBCHANGEJOBCFG
DESCRIPTOR.message_types_by_name['PBChangeJobCost'] = _PBCHANGEJOBCOST
DESCRIPTOR.message_types_by_name['PBRoleJuejiSKillBook'] = _PBROLEJUEJISKILLBOOK
DESCRIPTOR.message_types_by_name['PBSkillBookList'] = _PBSKILLBOOKLIST
DESCRIPTOR.message_types_by_name['PBChangeJobMoneyItem'] = _PBCHANGEJOBMONEYITEM
DESCRIPTOR.message_types_by_name['PBChangeJobZhenQiItem'] = _PBCHANGEJOBZHENQIITEM

class PBChangeJobCfg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCHANGEJOBCFG
  
  # @@protoc_insertion_point(class_scope:PBChangeJobCfg)

class PBChangeJobCost(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCHANGEJOBCOST
  
  # @@protoc_insertion_point(class_scope:PBChangeJobCost)

class PBRoleJuejiSKillBook(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBROLEJUEJISKILLBOOK
  
  # @@protoc_insertion_point(class_scope:PBRoleJuejiSKillBook)

class PBSkillBookList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSKILLBOOKLIST
  
  # @@protoc_insertion_point(class_scope:PBSkillBookList)

class PBChangeJobMoneyItem(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCHANGEJOBMONEYITEM
  
  # @@protoc_insertion_point(class_scope:PBChangeJobMoneyItem)

class PBChangeJobZhenQiItem(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCHANGEJOBZHENQIITEM
  
  # @@protoc_insertion_point(class_scope:PBChangeJobZhenQiItem)

# @@protoc_insertion_point(module_scope)
