# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_equip_attach.proto',
  package='',
  serialized_pb='\n\x17tmpl_equip_attach.proto\"\x86\x01\n\x10PBEquipAttachCfg\x12\x1c\n\x08lib_list\x18\x01 \x03(\x0b\x32\n.PBPropLib\x12/\n\x11\x65quip_attach_list\x18\x02 \x03(\x0b\x32\x14.PBEquipAttachOneCfg\x12#\n\x0eroll_rule_list\x18\x03 \x03(\x0b\x32\x0b.PBRollRule\"\x81\x02\n\x13PBEquipAttachOneCfg\x12\x16\n\x0evita_min_value\x18\x01 \x01(\x11\x12\x16\n\x0evita_max_value\x18\x02 \x01(\x11\x12\x17\n\x0f\x63ost_sheet_name\x18\x03 \x01(\t\x12\x12\n\ncost_count\x18\x04 \x01(\x11\x12\x13\n\x0b\x61\x64\x64_pro_num\x18\x05 \x01(\x11\x12\"\n\rcan_roll_prop\x18\x06 \x03(\x0b\x32\x0b.PBRoLLProp\x12\x19\n\x11\x62\x65tter_attach_num\x18\x07 \x01(\x11\x12\x1e\n\x16\x62\x65tter_cost_sheet_name\x18\x08 \x01(\t\x12\x19\n\x11\x62\x65tter_cost_count\x18\t \x01(\x11\"6\n\tPBPropLib\x12\x12\n\nprop_class\x18\x01 \x01(\x11\x12\x15\n\rprop_lib_name\x18\x02 \x01(\t\";\n\nPBRoLLProp\x12\x1b\n\x13\x63\x61n_roll_prop_class\x18\x01 \x01(\x11\x12\x10\n\x08roll_pro\x18\x02 \x01(\x11\"\x1e\n\nPBRollRule\x12\x10\n\x08roll_pro\x18\x01 \x01(\x11')




_PBEQUIPATTACHCFG = descriptor.Descriptor(
  name='PBEquipAttachCfg',
  full_name='PBEquipAttachCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='lib_list', full_name='PBEquipAttachCfg.lib_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='equip_attach_list', full_name='PBEquipAttachCfg.equip_attach_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roll_rule_list', full_name='PBEquipAttachCfg.roll_rule_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=162,
)


_PBEQUIPATTACHONECFG = descriptor.Descriptor(
  name='PBEquipAttachOneCfg',
  full_name='PBEquipAttachOneCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='vita_min_value', full_name='PBEquipAttachOneCfg.vita_min_value', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vita_max_value', full_name='PBEquipAttachOneCfg.vita_max_value', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cost_sheet_name', full_name='PBEquipAttachOneCfg.cost_sheet_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cost_count', full_name='PBEquipAttachOneCfg.cost_count', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='add_pro_num', full_name='PBEquipAttachOneCfg.add_pro_num', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='can_roll_prop', full_name='PBEquipAttachOneCfg.can_roll_prop', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='better_attach_num', full_name='PBEquipAttachOneCfg.better_attach_num', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='better_cost_sheet_name', full_name='PBEquipAttachOneCfg.better_cost_sheet_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='better_cost_count', full_name='PBEquipAttachOneCfg.better_cost_count', index=8,
      number=9, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=165,
  serialized_end=422,
)


_PBPROPLIB = descriptor.Descriptor(
  name='PBPropLib',
  full_name='PBPropLib',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='prop_class', full_name='PBPropLib.prop_class', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='prop_lib_name', full_name='PBPropLib.prop_lib_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=424,
  serialized_end=478,
)


_PBROLLPROP = descriptor.Descriptor(
  name='PBRoLLProp',
  full_name='PBRoLLProp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='can_roll_prop_class', full_name='PBRoLLProp.can_roll_prop_class', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roll_pro', full_name='PBRoLLProp.roll_pro', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=480,
  serialized_end=539,
)


_PBROLLRULE = descriptor.Descriptor(
  name='PBRollRule',
  full_name='PBRollRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='roll_pro', full_name='PBRollRule.roll_pro', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=541,
  serialized_end=571,
)

_PBEQUIPATTACHCFG.fields_by_name['lib_list'].message_type = _PBPROPLIB
_PBEQUIPATTACHCFG.fields_by_name['equip_attach_list'].message_type = _PBEQUIPATTACHONECFG
_PBEQUIPATTACHCFG.fields_by_name['roll_rule_list'].message_type = _PBROLLRULE
_PBEQUIPATTACHONECFG.fields_by_name['can_roll_prop'].message_type = _PBROLLPROP
DESCRIPTOR.message_types_by_name['PBEquipAttachCfg'] = _PBEQUIPATTACHCFG
DESCRIPTOR.message_types_by_name['PBEquipAttachOneCfg'] = _PBEQUIPATTACHONECFG
DESCRIPTOR.message_types_by_name['PBPropLib'] = _PBPROPLIB
DESCRIPTOR.message_types_by_name['PBRoLLProp'] = _PBROLLPROP
DESCRIPTOR.message_types_by_name['PBRollRule'] = _PBROLLRULE

class PBEquipAttachCfg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBEQUIPATTACHCFG
  
  # @@protoc_insertion_point(class_scope:PBEquipAttachCfg)

class PBEquipAttachOneCfg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBEQUIPATTACHONECFG
  
  # @@protoc_insertion_point(class_scope:PBEquipAttachOneCfg)

class PBPropLib(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBPROPLIB
  
  # @@protoc_insertion_point(class_scope:PBPropLib)

class PBRoLLProp(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBROLLPROP
  
  # @@protoc_insertion_point(class_scope:PBRoLLProp)

class PBRollRule(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBROLLRULE
  
  # @@protoc_insertion_point(class_scope:PBRollRule)

# @@protoc_insertion_point(module_scope)
