# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tmpl_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_channel_base.proto',
  package='',
  serialized_pb='\n\x17tmpl_channel_base.proto\x1a\x0ftmpl_base.proto\",\n\tPBReweard\x12\x12\n\nitem_sheet\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x11\"_\n\x10PBRewardRelation\x12\x1a\n\x06reward\x18\x01 \x03(\x0b\x32\n.PBReweard\x12\x11\n\tbegintime\x18\x02 \x01(\t\x12\x0f\n\x07\x65ndtime\x18\x03 \x01(\t\x12\x0b\n\x03idx\x18\x04 \x01(\x11\"l\n\nPBQQReward\x12)\n\x0erewardrelation\x18\x01 \x03(\x0b\x32\x11.PBRewardRelation\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x11\x12\x11\n\tall_begin\x18\x03 \x01(\t\x12\x0f\n\x07\x61ll_end\x18\x04 \x01(\t')




_PBREWEARD = descriptor.Descriptor(
  name='PBReweard',
  full_name='PBReweard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='item_sheet', full_name='PBReweard.item_sheet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num', full_name='PBReweard.num', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=88,
)


_PBREWARDRELATION = descriptor.Descriptor(
  name='PBRewardRelation',
  full_name='PBRewardRelation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reward', full_name='PBRewardRelation.reward', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='begintime', full_name='PBRewardRelation.begintime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endtime', full_name='PBRewardRelation.endtime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='idx', full_name='PBRewardRelation.idx', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=90,
  serialized_end=185,
)


_PBQQREWARD = descriptor.Descriptor(
  name='PBQQReward',
  full_name='PBQQReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rewardrelation', full_name='PBQQReward.rewardrelation', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channel', full_name='PBQQReward.channel', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='all_begin', full_name='PBQQReward.all_begin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='all_end', full_name='PBQQReward.all_end', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=187,
  serialized_end=295,
)

_PBREWARDRELATION.fields_by_name['reward'].message_type = _PBREWEARD
_PBQQREWARD.fields_by_name['rewardrelation'].message_type = _PBREWARDRELATION
DESCRIPTOR.message_types_by_name['PBReweard'] = _PBREWEARD
DESCRIPTOR.message_types_by_name['PBRewardRelation'] = _PBREWARDRELATION
DESCRIPTOR.message_types_by_name['PBQQReward'] = _PBQQREWARD

class PBReweard(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBREWEARD
  
  # @@protoc_insertion_point(class_scope:PBReweard)

class PBRewardRelation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBREWARDRELATION
  
  # @@protoc_insertion_point(class_scope:PBRewardRelation)

class PBQQReward(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBQQREWARD
  
  # @@protoc_insertion_point(class_scope:PBQQReward)

# @@protoc_insertion_point(module_scope)
