# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tmpl_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_pve_match.proto',
  package='',
  serialized_pb='\n\x14tmpl_pve_match.proto\x1a\x0ftmpl_base.proto\"4\n\rPBPvEMatchCfg\x12#\n\x07\x64ungeon\x18\x01 \x03(\x0b\x32\x12.PBPvEMatchDungeon\"z\n\x11PBPvEMatchDungeon\x12\x15\n\rdungeon_sheet\x18\x01 \x01(\t\x12\x12\n\nmatch_time\x18\x02 \x01(\x11\x12\x13\n\x0bmatch_level\x18\x03 \x01(\x11\x12%\n\x08\x63reature\x18\x04 \x03(\x0b\x32\x13.PBPvEMatchCreature\"X\n\x12PBPvEMatchCreature\x12\x16\n\x0e\x63reature_sheet\x18\x01 \x01(\t\x12\x12\n\ngroup_name\x18\x02 \x01(\t\x12\x16\n\x0e\x63reature_level\x18\x03 \x01(\x11')




_PBPVEMATCHCFG = descriptor.Descriptor(
  name='PBPvEMatchCfg',
  full_name='PBPvEMatchCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dungeon', full_name='PBPvEMatchCfg.dungeon', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=93,
)


_PBPVEMATCHDUNGEON = descriptor.Descriptor(
  name='PBPvEMatchDungeon',
  full_name='PBPvEMatchDungeon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dungeon_sheet', full_name='PBPvEMatchDungeon.dungeon_sheet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='match_time', full_name='PBPvEMatchDungeon.match_time', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='match_level', full_name='PBPvEMatchDungeon.match_level', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='creature', full_name='PBPvEMatchDungeon.creature', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=217,
)


_PBPVEMATCHCREATURE = descriptor.Descriptor(
  name='PBPvEMatchCreature',
  full_name='PBPvEMatchCreature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='creature_sheet', full_name='PBPvEMatchCreature.creature_sheet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group_name', full_name='PBPvEMatchCreature.group_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='creature_level', full_name='PBPvEMatchCreature.creature_level', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=219,
  serialized_end=307,
)

_PBPVEMATCHCFG.fields_by_name['dungeon'].message_type = _PBPVEMATCHDUNGEON
_PBPVEMATCHDUNGEON.fields_by_name['creature'].message_type = _PBPVEMATCHCREATURE
DESCRIPTOR.message_types_by_name['PBPvEMatchCfg'] = _PBPVEMATCHCFG
DESCRIPTOR.message_types_by_name['PBPvEMatchDungeon'] = _PBPVEMATCHDUNGEON
DESCRIPTOR.message_types_by_name['PBPvEMatchCreature'] = _PBPVEMATCHCREATURE

class PBPvEMatchCfg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBPVEMATCHCFG
  
  # @@protoc_insertion_point(class_scope:PBPvEMatchCfg)

class PBPvEMatchDungeon(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBPVEMATCHDUNGEON
  
  # @@protoc_insertion_point(class_scope:PBPvEMatchDungeon)

class PBPvEMatchCreature(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBPVEMATCHCREATURE
  
  # @@protoc_insertion_point(class_scope:PBPvEMatchCreature)

# @@protoc_insertion_point(module_scope)
