# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tmpl_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_static_string.proto',
  package='',
  serialized_pb='\n\x18tmpl_static_string.proto\x1a\x0ftmpl_base.proto\";\n\x14PBServerStaticString\x12#\n\npb_strings\x18\x01 \x03(\x0b\x32\x0f.PBStaticString\",\n\x0ePBStaticString\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t')




_PBSERVERSTATICSTRING = descriptor.Descriptor(
  name='PBServerStaticString',
  full_name='PBServerStaticString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pb_strings', full_name='PBServerStaticString.pb_strings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=104,
)


_PBSTATICSTRING = descriptor.Descriptor(
  name='PBStaticString',
  full_name='PBStaticString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='PBStaticString.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='PBStaticString.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=106,
  serialized_end=150,
)

_PBSERVERSTATICSTRING.fields_by_name['pb_strings'].message_type = _PBSTATICSTRING
DESCRIPTOR.message_types_by_name['PBServerStaticString'] = _PBSERVERSTATICSTRING
DESCRIPTOR.message_types_by_name['PBStaticString'] = _PBSTATICSTRING

class PBServerStaticString(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSERVERSTATICSTRING
  
  # @@protoc_insertion_point(class_scope:PBServerStaticString)

class PBStaticString(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSTATICSTRING
  
  # @@protoc_insertion_point(class_scope:PBStaticString)

# @@protoc_insertion_point(module_scope)
