# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tmpl_base_pb2
import msg_common_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_func_hide.proto',
  package='',
  serialized_pb='\n\x14tmpl_func_hide.proto\x1a\x0ftmpl_base.proto\x1a\x10msg_common.proto\"I\n\x14PBConfigGameFuncHide\x12\x19\n\x04\x66unc\x18\x01 \x03(\x0b\x32\x0b.PBFuncHide:\x16\xc2\xf3\x18\x12game_func_hide.xml\"t\n\nPBFuncHide\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\x12\x12\n\ngateway_id\x18\x02 \x01(\x05\x12\x11\n\tfunc_name\x18\x03 \x01(\t\x12\x16\n\x0e\x66unc_param_int\x18\x04 \x03(\x05\x12\x16\n\x0e\x66unc_param_str\x18\x05 \x03(\t')




_PBCONFIGGAMEFUNCHIDE = descriptor.Descriptor(
  name='PBConfigGameFuncHide',
  full_name='PBConfigGameFuncHide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='func', full_name='PBConfigGameFuncHide.func', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=descriptor._ParseOptions(descriptor_pb2.MessageOptions(), '\302\363\030\022game_func_hide.xml'),
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=132,
)


_PBFUNCHIDE = descriptor.Descriptor(
  name='PBFuncHide',
  full_name='PBFuncHide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='game_id', full_name='PBFuncHide.game_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gateway_id', full_name='PBFuncHide.gateway_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='func_name', full_name='PBFuncHide.func_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='func_param_int', full_name='PBFuncHide.func_param_int', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='func_param_str', full_name='PBFuncHide.func_param_str', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=250,
)

_PBCONFIGGAMEFUNCHIDE.fields_by_name['func'].message_type = _PBFUNCHIDE
DESCRIPTOR.message_types_by_name['PBConfigGameFuncHide'] = _PBCONFIGGAMEFUNCHIDE
DESCRIPTOR.message_types_by_name['PBFuncHide'] = _PBFUNCHIDE

class PBConfigGameFuncHide(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCONFIGGAMEFUNCHIDE
  
  # @@protoc_insertion_point(class_scope:PBConfigGameFuncHide)

class PBFuncHide(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBFUNCHIDE
  
  # @@protoc_insertion_point(class_scope:PBFuncHide)

# @@protoc_insertion_point(module_scope)
