# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tmpl_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_camp_chat.proto',
  package='',
  serialized_pb='\n\x14tmpl_camp_chat.proto\x1a\x0ftmpl_base.proto\"W\n\rPBCampChatCfg\x12\x1a\n\x12limit_cancel_level\x18\x01 \x01(\x11\x12*\n\x0blevel_table\x18\x02 \x03(\x0b\x32\x15.PBCampChatLevelTable\"=\n\x14PBCampChatLevelTable\x12\r\n\x05level\x18\x01 \x01(\x11\x12\x16\n\x0emaxchatallowed\x18\x02 \x01(\x11')




_PBCAMPCHATCFG = descriptor.Descriptor(
  name='PBCampChatCfg',
  full_name='PBCampChatCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='limit_cancel_level', full_name='PBCampChatCfg.limit_cancel_level', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level_table', full_name='PBCampChatCfg.level_table', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=128,
)


_PBCAMPCHATLEVELTABLE = descriptor.Descriptor(
  name='PBCampChatLevelTable',
  full_name='PBCampChatLevelTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='level', full_name='PBCampChatLevelTable.level', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxchatallowed', full_name='PBCampChatLevelTable.maxchatallowed', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=130,
  serialized_end=191,
)

_PBCAMPCHATCFG.fields_by_name['level_table'].message_type = _PBCAMPCHATLEVELTABLE
DESCRIPTOR.message_types_by_name['PBCampChatCfg'] = _PBCAMPCHATCFG
DESCRIPTOR.message_types_by_name['PBCampChatLevelTable'] = _PBCAMPCHATLEVELTABLE

class PBCampChatCfg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCAMPCHATCFG
  
  # @@protoc_insertion_point(class_scope:PBCampChatCfg)

class PBCampChatLevelTable(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCAMPCHATLEVELTABLE
  
  # @@protoc_insertion_point(class_scope:PBCampChatLevelTable)

# @@protoc_insertion_point(module_scope)
