# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import google.protobuf.descriptor_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_base.proto',
  package='',
  serialized_pb='\n\x0ftmpl_base.proto\x1a google/protobuf/descriptor.proto\"H\n\x10PBConfigTemplate\x12\x1f\n\x06\x63onfig\x18\x01 \x03(\x0b\x32\x0f.PBTemplateData:\x13\xc2\xf3\x18\x0f\x63onfig_path.xml\"/\n\x0ePBTemplateData\x12\x0f\n\x07pb_name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"(\n\x10PBTemplateVector\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"T\n\x16PBTemplateItemQuantity\x12\x12\n\nsheet_name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x11\x12\x17\n\x0f\x63onsume_funtion\x18\x03 \x01(\t\"*\n\x12PBTemplateVector2d\x12\t\n\x01x\x18\x01 \x01(\x11\x12\t\n\x01y\x18\x02 \x01(\x11\"C\n\x1aPBTemplateItemQuantityList\x12%\n\x04item\x18\x01 \x03(\x0b\x32\x17.PBTemplateItemQuantity:8\n\rOptionXmlFile\x12\x1f.google.protobuf.MessageOptions\x18\xb8\x8e\x03 \x01(\t:8\n\rOptionXmlOnly\x12\x1f.google.protobuf.MessageOptions\x18\xb9\x8e\x03 \x01(\x08:9\n\x10OptionServerOnly\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xdc\x03 \x01(\x08:7\n\nOptionHint\x12!.google.protobuf.EnumValueOptions\x18\xd8\xaa\x04 \x01(\tB\x02H\x01')


OPTIONXMLFILE_FIELD_NUMBER = 51000
OptionXmlFile = descriptor.FieldDescriptor(
  name='OptionXmlFile', full_name='OptionXmlFile', index=0,
  number=51000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
OPTIONXMLONLY_FIELD_NUMBER = 51001
OptionXmlOnly = descriptor.FieldDescriptor(
  name='OptionXmlOnly', full_name='OptionXmlOnly', index=1,
  number=51001, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
OPTIONSERVERONLY_FIELD_NUMBER = 61000
OptionServerOnly = descriptor.FieldDescriptor(
  name='OptionServerOnly', full_name='OptionServerOnly', index=2,
  number=61000, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
OPTIONHINT_FIELD_NUMBER = 71000
OptionHint = descriptor.FieldDescriptor(
  name='OptionHint', full_name='OptionHint', index=3,
  number=71000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_PBCONFIGTEMPLATE = descriptor.Descriptor(
  name='PBConfigTemplate',
  full_name='PBConfigTemplate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='config', full_name='PBConfigTemplate.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=descriptor._ParseOptions(descriptor_pb2.MessageOptions(), '\302\363\030\017config_path.xml'),
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=125,
)


_PBTEMPLATEDATA = descriptor.Descriptor(
  name='PBTemplateData',
  full_name='PBTemplateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pb_name', full_name='PBTemplateData.pb_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='path', full_name='PBTemplateData.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=127,
  serialized_end=174,
)


_PBTEMPLATEVECTOR = descriptor.Descriptor(
  name='PBTemplateVector',
  full_name='PBTemplateVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='PBTemplateVector.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='PBTemplateVector.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=176,
  serialized_end=216,
)


_PBTEMPLATEITEMQUANTITY = descriptor.Descriptor(
  name='PBTemplateItemQuantity',
  full_name='PBTemplateItemQuantity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sheet_name', full_name='PBTemplateItemQuantity.sheet_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='PBTemplateItemQuantity.count', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='consume_funtion', full_name='PBTemplateItemQuantity.consume_funtion', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=218,
  serialized_end=302,
)


_PBTEMPLATEVECTOR2D = descriptor.Descriptor(
  name='PBTemplateVector2d',
  full_name='PBTemplateVector2d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='PBTemplateVector2d.x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='PBTemplateVector2d.y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=304,
  serialized_end=346,
)


_PBTEMPLATEITEMQUANTITYLIST = descriptor.Descriptor(
  name='PBTemplateItemQuantityList',
  full_name='PBTemplateItemQuantityList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='item', full_name='PBTemplateItemQuantityList.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=348,
  serialized_end=415,
)

_PBCONFIGTEMPLATE.fields_by_name['config'].message_type = _PBTEMPLATEDATA
_PBTEMPLATEITEMQUANTITYLIST.fields_by_name['item'].message_type = _PBTEMPLATEITEMQUANTITY
DESCRIPTOR.message_types_by_name['PBConfigTemplate'] = _PBCONFIGTEMPLATE
DESCRIPTOR.message_types_by_name['PBTemplateData'] = _PBTEMPLATEDATA
DESCRIPTOR.message_types_by_name['PBTemplateVector'] = _PBTEMPLATEVECTOR
DESCRIPTOR.message_types_by_name['PBTemplateItemQuantity'] = _PBTEMPLATEITEMQUANTITY
DESCRIPTOR.message_types_by_name['PBTemplateVector2d'] = _PBTEMPLATEVECTOR2D
DESCRIPTOR.message_types_by_name['PBTemplateItemQuantityList'] = _PBTEMPLATEITEMQUANTITYLIST

class PBConfigTemplate(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCONFIGTEMPLATE
  
  # @@protoc_insertion_point(class_scope:PBConfigTemplate)

class PBTemplateData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBTEMPLATEDATA
  
  # @@protoc_insertion_point(class_scope:PBTemplateData)

class PBTemplateVector(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBTEMPLATEVECTOR
  
  # @@protoc_insertion_point(class_scope:PBTemplateVector)

class PBTemplateItemQuantity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBTEMPLATEITEMQUANTITY
  
  # @@protoc_insertion_point(class_scope:PBTemplateItemQuantity)

class PBTemplateVector2d(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBTEMPLATEVECTOR2D
  
  # @@protoc_insertion_point(class_scope:PBTemplateVector2d)

class PBTemplateItemQuantityList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBTEMPLATEITEMQUANTITYLIST
  
  # @@protoc_insertion_point(class_scope:PBTemplateItemQuantityList)

google.protobuf.descriptor_pb2.MessageOptions.RegisterExtension(OptionXmlFile)
google.protobuf.descriptor_pb2.MessageOptions.RegisterExtension(OptionXmlOnly)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(OptionServerOnly)
google.protobuf.descriptor_pb2.EnumValueOptions.RegisterExtension(OptionHint)
# @@protoc_insertion_point(module_scope)
