# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tmpl_base_pb2
import msg_common_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='tmpl_friend.proto',
  package='',
  serialized_pb='\n\x11tmpl_friend.proto\x1a\x0ftmpl_base.proto\x1a\x10msg_common.proto\"\xd8\x01\n\x10PBFriendValueCfg\x12\x12\n\nmax_friend\x18\x01 \x01(\x11\x12\x11\n\tmax_black\x18\x02 \x01(\x11\x12\x14\n\x0cmax_negative\x18\x03 \x01(\x11\x12\x11\n\tmax_enemy\x18\x04 \x01(\x11\x12\x17\n\x0fmost_friend_num\x18\x05 \x01(\x11\x12\x14\n\x0chead_icon_cd\x18\x06 \x01(\x11\x12\x16\n\x0ehead_icon_open\x18\x07 \x01(\x11\x12\x18\n\x10head_icon_length\x18\x08 \x01(\x11\x12\x13\n\x0bmax_contact\x18\t \x01(\x11\"6\n\x0ePBFriendConfig\x12$\n\tvalue_cfg\x18\x01 \x01(\x0b\x32\x11.PBFriendValueCfg')




_PBFRIENDVALUECFG = descriptor.Descriptor(
  name='PBFriendValueCfg',
  full_name='PBFriendValueCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='max_friend', full_name='PBFriendValueCfg.max_friend', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_black', full_name='PBFriendValueCfg.max_black', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_negative', full_name='PBFriendValueCfg.max_negative', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_enemy', full_name='PBFriendValueCfg.max_enemy', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='most_friend_num', full_name='PBFriendValueCfg.most_friend_num', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head_icon_cd', full_name='PBFriendValueCfg.head_icon_cd', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head_icon_open', full_name='PBFriendValueCfg.head_icon_open', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head_icon_length', full_name='PBFriendValueCfg.head_icon_length', index=7,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_contact', full_name='PBFriendValueCfg.max_contact', index=8,
      number=9, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=273,
)


_PBFRIENDCONFIG = descriptor.Descriptor(
  name='PBFriendConfig',
  full_name='PBFriendConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value_cfg', full_name='PBFriendConfig.value_cfg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=275,
  serialized_end=329,
)

_PBFRIENDCONFIG.fields_by_name['value_cfg'].message_type = _PBFRIENDVALUECFG
DESCRIPTOR.message_types_by_name['PBFriendValueCfg'] = _PBFRIENDVALUECFG
DESCRIPTOR.message_types_by_name['PBFriendConfig'] = _PBFRIENDCONFIG

class PBFriendValueCfg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBFRIENDVALUECFG
  
  # @@protoc_insertion_point(class_scope:PBFriendValueCfg)

class PBFriendConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBFRIENDCONFIG
  
  # @@protoc_insertion_point(class_scope:PBFriendConfig)

# @@protoc_insertion_point(module_scope)
